$ErrorActionPreference = "Stop"

function Assert-Contains([string]$relativePath, [string]$pattern, [string]$message) {
    $path = Join-Path (Get-Location) $relativePath
    $text = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    if ($text -notmatch $pattern) {
        throw "ERROR: ${relativePath}: ${message}"
    }
}

$spider = "gmod_addon\lua\entities\bmb_spider.lua"
$base = "gmod_addon\lua\entities\bmb_base_mob.lua"
$pathfinder = "gmod_addon\lua\bmb\sv_pathfinder.lua"
$behaviors = "gmod_addon\lua\bmb\sv_behaviors.lua"

Assert-Contains $spider 'WalkSpeed\s*=\s*100' "Spider wander speed should use the tuned 100 default."
Assert-Contains $spider 'RunSpeed\s*=\s*140' "Spider chase speed should use the tuned 140 default."
Assert-Contains $spider 'AttackMoveSpeed\s*=\s*140' "Spider close attack pressure should keep pace with the tuned chase speed."

Assert-Contains $spider 'bmb_spider_climb_cancel_cooldown",\s*"1\.6"' "Spider Phase 3 should cooldown after target-aware climb cancellation."
Assert-Contains $spider 'bmb_spider_climb_chase_min_target_up",\s*"18"' "Spider Phase 3 should require a target height advantage before chase climb starts."
Assert-Contains $spider 'bmb_spider_climb_chase_wall_dot",\s*"0\.1"' "Spider Phase 3 should require chase targets to be roughly beyond the climbed wall."
Assert-Contains $spider 'bmb_spider_climb_chase_cancel_grace",\s*"0\.45"' "Spider Phase 3 should expose a grace window before cancelling an active climb."
Assert-Contains $spider 'bmb_spider_climb_chase_active",\s*"1"' "Spider Phase 3 should enable proactive chase climb routing by default."
Assert-Contains $spider 'bmb_spider_climb_chase_approach_distance",\s*"260"' "Spider Phase 3 should expose proactive climb wall scan distance."
Assert-Contains $spider 'bmb_spider_climb_chase_approach_timeout",\s*"0\.45"' "Spider Phase 3 should expose proactive climb approach segment time."
Assert-Contains $spider 'bmb_spider_climb_chase_start_distance",\s*"84"' "Spider Phase 3 should start climbing immediately when a proactive wall hit is close enough."
Assert-Contains $spider 'bmb_spider_climb_max_cells",\s*"6"' "Spider Phase 3 should expose the A* climb edge height limit."
Assert-Contains $spider 'bmb_spider_climb_edge_cost",\s*"2\.5"' "Spider Phase 3 should expose the A* climb edge cost."
Assert-Contains $spider 'bmb_spider_climb_horizontal_cells",\s*"2"' "Spider Phase 3 should expose the wide-hull horizontal climb start range."
Assert-Contains $spider 'bmb_spider_prefer_climb_over_hop",\s*"0"' "Spider climb-over-hop preference should default off so one-block crawl entrances stay routeable."

Assert-Contains $spider 'function ENT:GetBMBSpiderClimbCombatTarget\(\)' "Spider Phase 3 should resolve the current retaliation target for climb decisions."
Assert-Contains $spider 'function ENT:GetBMBSpiderClimbTargetPosition\(target\)' "Spider Phase 3 should bias wall scans toward the current combat or movement target."
Assert-Contains $spider 'function ENT:IsBMBSpiderLowChaseClimbReason\(reason\)' "Spider chase climb should allow blocked low-wall path/direct movement to enter the climb spike."
Assert-Contains $spider 'reason == "path_carrot"' "Spider low-wall climb should cover A* path carrot blockage."
Assert-Contains $spider 'reason == "direct"' "Spider low-wall climb should cover direct chase blockage."
Assert-Contains $spider 'reason == "chase_active_blocked"' "Spider low-wall climb should cover proactive chase blockage."
Assert-Contains $spider 'function ENT:ShouldBMBSpiderStartClimb\(target,\s*normal,\s*reason\)' "Spider Phase 3 should gate climb startup instead of climbing every wall during chase."
Assert-Contains $spider 'targetUp\s*<\s*minTargetUp and not lowChaseClimb' "Spider high-target chase climb should still require height, while low-wall blockage may climb."
Assert-Contains $spider 'dot\s*<\s*minDot' "Spider chase climb should reject walls that are not between the spider and its target."

Assert-Contains $spider 'function ENT:ShouldCancelBMBSpiderChaseClimb\(normal\)' "Spider Phase 3 should re-check target state while already climbing."
Assert-Contains $spider 'BMBSpiderClimbCancelCheckAt' "Spider climb should wait a short grace period before target-aware cancellation."
Assert-Contains $spider 'not self\.BMBSpiderClimbAllowLowTarget and targetPos\.z\s*-\s*startZ\s*<\s*minTargetUp\s*\*\s*0\.5' "Spider high-target climb should cancel if the target drops, but low-wall climb should finish."
Assert-Contains $spider 'BMBSpiderClimbAllowLowTarget\s*=\s*self:IsBMBSpiderLowChaseClimbReason\(reason\)' "Spider climb should remember low-wall startup so cancellation does not abort same-height mantles."
Assert-Contains $spider 'targetDirection:Dot\(intoWall\)\s*<\s*-0\.35' "Spider climb should cancel if the chase target clearly moves away from the climbed wall."
Assert-Contains $spider 'FinishBMBSpiderClimbSpike\(cancelReason or "target_lost"\)' "Spider climb should restore normal locomotion when chase cancellation fires."
Assert-Contains $spider 'GetBMBSpiderClimbCancelCooldown\(\)' "Target-aware climb cancellation should have its own retry cooldown."

Assert-Contains $spider 'function ENT:ShouldRunBMBSpiderChaseClimb\(target\)' "Spider Phase 3 should decide when a high chase target deserves proactive climb routing."
Assert-Contains $spider 'function ENT:GetBMBSpiderChaseClimbDirections\(target\)' "Spider Phase 3 should use a fan of target/forward/side directions for high-target wall scans."
Assert-Contains $spider 'function ENT:TryBMBSpiderChaseClimbAtWall\(target,\s*normal,\s*reason\)' "Spider Phase 3 should be able to start climb from a wall normal found by proactive chase scan."
Assert-Contains $spider 'function ENT:FindBMBSpiderChaseClimbApproach\(target\)' "Spider Phase 3 should find a wall approach point before ordinary chase stalls below high targets."
Assert-Contains $spider 'function ENT:RunBMBSpiderChaseClimb\(target\)' "Spider Phase 3 should own a proactive chase climb entry point."
Assert-Contains $spider 'self:SetBMBMoveMode\("chase_climb_approach"\)' "Spider proactive climb should expose a chase_climb_approach debug move mode."
Assert-Contains $spider 'MoveToWorldPosition\(approach,\s*speed,\s*\{(?s).*allowDirectFallback\s*=\s*true' "Spider proactive climb should walk to the wall foot before the climb spike takes over."
Assert-Contains $spider 'RunBMBSpiderChaseClimb\(self\.TargetEntity\)' "Spider AI should try proactive climbing before falling back to shared chase."
Assert-Contains $spider 'BMBSpiderClimbForcedNormal' "Spider proactive climb should preserve a detected wall normal so direct blocked frontal cases can enter climb."
Assert-Contains $spider 'approachDistance\s*<=\s*startDistance' "Spider proactive climb should skip wall-foot movement and climb immediately when already close to the wall."
Assert-Contains $spider 'skip climb start: wall not pinned' "Spider climb should not enter climb_spike until the current position can actually pin to the wall."
Assert-Contains $spider 'BMBSpiderClimbLastPinnedPos\s*=\s*startPinned' "Spider climb should seed the spike from the first pinned wall position, not a too-far pre-wall position."

Assert-Contains $spider 'BMBSpiderClimbPendingReason\s*=\s*reason' "Movement override should pass its reason into the climb spike without changing the Phase 1 function signature."
Assert-Contains $spider 'reason\s*=\s*self\.BMBSpiderClimbPendingReason or "ambient"' "Ambient climb attempts should be distinguishable from movement override climb attempts."
Assert-Contains $spider 'scanTarget\s*=\s*targetPos or target' "Wall scanning should prefer the resolved combat target position when one exists."
Assert-Contains $spider 'function ENT:ConfigureBMBPathfinderOptions\(pathOptions' "Spider should opt into climb-aware pathfinder options."
Assert-Contains $spider 'pathOptions\.allowClimb\s*=\s*true' "Spider pathfinder options should enable climb edges."
Assert-Contains $spider 'function ENT:ShouldBMBSpiderPreferClimbOverHop\(\)' "Spider should gate climb-over-hop preference behind an explicit toggle."
Assert-Contains $spider 'if self:ShouldBMBSpiderPreferClimbOverHop\(\) then(?s).*pathOptions\.preferClimbOverHop\s*=\s*true' "Spider should only suppress duplicate hop edges when the toggle is enabled."
Assert-Contains $spider 'function ENT:RunBMBPathVerticalAction\(action,\s*node,\s*final' "Spider should execute path climb waypoints through the base vertical-action hook."
Assert-Contains $spider 'BMBSpiderClimbPendingReason\s*=\s*"path_climb"' "Spider A* climb should use a distinct path_climb reason."
Assert-Contains $spider 'BMBSpiderLastClimbResult\s*==\s*"success"' "Spider path climb should only advance the A* node after a successful spike."
Assert-Contains $spider 'reason\s*==\s*"path_climb"' "Spider path climb should bypass chase-only high-target startup gating."
Assert-Contains $spider 'function ENT:ApproachBMBSpiderPathClimbWall\(normal,\s*speed\)' "Spider path climb should approach from a wide-hull-safe A* cell before starting the spike."
Assert-Contains $spider 'self:SetBMBMoveMode\("path_climb_approach"\)' "Spider path climb approach should publish a debug move mode."

Assert-Contains $pathfinder 'options\.allowClimb\s*~=\s*true' "Pathfinder climb neighbors must be gated behind explicit spider opt-in."
Assert-Contains $pathfinder 'function\s+getClimbHorizontalCells\(options\)' "Pathfinder climb neighbors should account for wide mobs that cannot stand in the wall-adjacent cell."
Assert-Contains $pathfinder 'action\s*=\s*action or "walk"' "Pathfinder neighbor records should keep explicit action metadata."
Assert-Contains $pathfinder '"climb",\s*getClimbEdgeCost\(options\) \* climbCells' "Pathfinder should emit high-cost climb edges."
Assert-Contains $pathfinder 'preferClimbOverHop\s*==\s*true' "Pathfinder should let spider-family mobs suppress a duplicate hop when climb reaches the same target cell."
Assert-Contains $pathfinder 'climbTargetKey\s*~=\s*coordKey\(hopTarget\)' "Pathfinder should only suppress hop when it duplicates the climb target."
Assert-Contains $pathfinder 'wallNormal\s*=\s*\{\s*x\s*=\s*-direction\.x' "Pathfinder climb edges should carry the wall normal needed by the spike."
Assert-Contains $pathfinder 'climbHeight\s*=\s*climbCells' "Pathfinder climb edges should preserve climb height metadata."
Assert-Contains $pathfinder 'climbApproachCells\s*=\s*climbOutCells' "Pathfinder climb edges should preserve horizontal approach metadata."
Assert-Contains $pathfinder 'cameMeta' "Pathfinder should carry climb metadata through A* reconstruction."

Assert-Contains $base 'function ENT:BuildBMBPathfinderOptions\(destination,\s*moveOptions\)' "Base mob should centralize pathfinder option forwarding."
Assert-Contains $base 'allowNearestGoal\s*=\s*moveOptions\.allowNearestGoal' "Base pathfinder options should forward chase nearest-goal settings."
Assert-Contains $base 'allowClimb\s*=\s*moveOptions\.allowClimb' "Base pathfinder options should forward climb opt-in."
Assert-Contains $base 'climbHorizontalCells\s*=\s*moveOptions\.climbHorizontalCells' "Base pathfinder options should forward spider climb horizontal range."
Assert-Contains $base 'action == "hop" or action == "drop" or action == "climb"' "Base movement should classify climb as a vertical path action."
Assert-Contains $base 'RunBMBPathVerticalAction\(activeAction,\s*actionNode,\s*final' "Base movement should delegate climb execution to the entity hook."

Assert-Contains $behaviors 'bmb_chase_wall_memory_cooldown' "Shared chase should expose a short wall-memory cooldown."
Assert-Contains $behaviors 'RememberDirectCliffBlock\(mob,\s*target,\s*reason\)' "Shared chase direct memory should record wall and cliff reasons."
Assert-Contains $behaviors 'reason == "wall"' "Shared chase direct memory should distinguish wall hits from cliff hits."
Assert-Contains $behaviors 'allowClimb\s*=\s*useClimbPath' "Shared chase should pass spider climb opt-in into path movement."
Assert-Contains $behaviors 'ShouldStalkHighTarget\(mob,\s*target\) and not useClimbPath' "Shared chase should stalk high targets before A* only for non-climbing mobs."

Write-Host "Spider Phase 3 checks passed."
