$ErrorActionPreference = "Stop"

function Assert-Contains([string]$relativePath, [string]$pattern, [string]$message) {
    $path = Join-Path (Get-Location) $relativePath
    $text = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    if ($text -notmatch $pattern) {
        throw "ERROR: ${relativePath}: ${message}"
    }
}

function Assert-NotContains([string]$relativePath, [string]$pattern, [string]$message) {
    $path = Join-Path (Get-Location) $relativePath
    $text = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    if ($text -match $pattern) {
        throw "ERROR: ${relativePath}: ${message}"
    }
}

$wolf = "gmod_addon\lua\entities\bmb_wolf.lua"
$menu = "gmod_addon\lua\autorun\mcgm_autorun.lua"
$base = "gmod_addon\lua\entities\bmb_base_mob.lua"
$behaviors = "gmod_addon\lua\bmb\sv_behaviors.lua"

Assert-Contains $wolf 'ENT\.Base\s*=\s*"bmb_base_mob"' "Wolf Phase 0 must be a real BMB NextBot, not the old base_anim stub."
Assert-Contains $wolf 'ENT\.Type\s*=\s*"nextbot"' "Wolf Phase 0 must spawn as a NextBot."
Assert-Contains $wolf 'ENT\.Model\s*=\s*"models/mcgm/wolf/wolf\.mdl"' "Wolf must reference the converted MC wolf model path."
Assert-Contains $wolf 'ENT\.Spawnable\s*=\s*true' "Wolf should be spawnable for Phase 0 testing."
Assert-NotContains $wolf 'base_anim|cube025x025x025|Stub Wolf' "The old flee-test box stub must not come back."

Assert-Contains $wolf 'function ENT:RunBehaviour\(\)' "Wolf should own a thin behavior scheduler."
Assert-Contains $wolf 'MaintainBMBFreeze' "Wolf should respect bmb_freeze for screenshots."
Assert-Contains $wolf 'RunBMBDebugMove' "Wolf should support the BMB debug movement tool."
Assert-Contains $wolf 'RunBMBStrandedRecovery' "Wolf should use base stranded recovery on invalid supports."
Assert-Contains $wolf 'RunBMBInitialIdle' "Wolf should idle briefly after spawn before wandering."
Assert-Contains $wolf 'BMB\.Behaviors\.Wander\.Run\(self\)' "Wolf should still fall back to wander when it has no prey."
Assert-Contains $wolf 'WolfPreyClasses' "Wolf Phase 1 should use an explicit prey class allowlist."
Assert-Contains $wolf 'bmb_sheep\s*=\s*true' "Wolf Phase 1 should actively hunt sheep."
Assert-Contains $wolf 'bmb_skeleton\s*=\s*true' "Wolf Phase 1 should actively hunt skeletons."
Assert-Contains $wolf 'bmb_stray\s*=\s*true' "Wolf Phase 1 should actively hunt Stray."
Assert-Contains $wolf 'bmb_parched\s*=\s*true' "Wolf Phase 1 should actively hunt Parched/Jiao Hai."
Assert-Contains $wolf 'bmb_bogged\s*=\s*true' "Wolf Phase 1 should actively hunt Bogged as a skeleton-family prey."
Assert-Contains $wolf 'function ENT:FindNearestWolfPrey' "Wolf Phase 1 should own a prey scanner instead of using player-only SeekTarget.Find."
Assert-Contains $wolf 'function ENT:ShouldBreakBMBWolfInitialIdle\(\)' "Wolf should be able to react immediately to prey or retaliation during its spawn idle."
Assert-Contains $wolf 'self\.BMBRetaliationTarget' "Wolf spawn idle should break immediately when damage retaliation provides a target."
Assert-Contains $wolf 'self:FindNearestWolfPrey\(self\.TargetEntity\)' "Wolf spawn idle should scan prey instead of waiting for the initial idle timer to expire."
Assert-Contains $wolf 'self\.BMBInitialIdleUntil\s*=\s*0' "Wolf should clear initial idle as soon as it finds prey or a retaliation target."
Assert-Contains $wolf 'BMB\.Behaviors\.Chase\.Run\(self,\s*self\.TargetEntity\)' "Wolf Phase 1 should reuse shared Chase for prey pursuit."
Assert-Contains $wolf 'BMB\.Behaviors\.MeleeAttack\.Try\(self,\s*self\.TargetEntity\)' "Wolf Phase 1 should reuse shared MeleeAttack for bites."
Assert-Contains $wolf 'ENT\.AttackDamage\s*=\s*10' "Wolf bite should deal 10 HP per hit."
Assert-Contains $wolf 'WolfRetaliatePlayers\s*=\s*true' "Wolf Phase 2 should expose an entity switch for retaliating against player attacks."
Assert-Contains $wolf 'CreateConVar\(\s*"bmb_wolf_retaliate_players"' "Wolf Phase 2 should expose a server cvar to disable player retaliation before tame-state rules land."
Assert-Contains $wolf 'function ENT:ShouldBMBWolfRetaliatePlayer\(target\)' "Wolf Phase 2 should accept players for the base damage-retaliation gate."
Assert-Contains $wolf 'return self:IsBMBCombatTarget\(target\)' "Wolf player retaliation should still use the base combat target validity gate."
Assert-Contains $wolf 'self:IsBMBWolfPrey\(ent\)\s*and\s*BMB\.Behaviors\.SeekTarget\.IsValid\(self,\s*ent,\s*range\)' "Wolf active scans must stay prey-only and not start hunting nearby players."
Assert-Contains $behaviors 'BMB\.Behaviors\.Leap\s*=\s*BMB\.Behaviors\.Leap or \{\}' "Wolf Phase 3 should add leap as a shared behavior module."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Leap\.Try\(mob,\s*target\)' "Wolf Phase 3 should expose shared Leap.Try."
Assert-Contains $behaviors 'Leap\.IsEligible' "Shared leap should keep eligibility separate from launch."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Leap\.IsPathClear\(mob,\s*target,\s*direction,\s*distance\)' "Shared leap should have a wall/block path-clear check separate from cliff support checks."
Assert-Contains $behaviors 'LeapIgnoreCliff' "Shared leap should be able to ignore cliff/support checks while still blocking walls."
Assert-Contains $behaviors 'return false,\s*"blocked"' "Shared leap should reject blocked wall/body paths."
Assert-Contains $behaviors 'mob\.loco:Jump\(\)' "Shared leap should use NextBot jump state for launch."
Assert-Contains $behaviors 'mob\.loco:SetVelocity\(velocity\)' "Shared leap should write a bounded launch velocity."
Assert-Contains $wolf 'ENT\.LeapEnabled\s*=\s*true' "Wolf Phase 3 should opt into shared leap."
Assert-Contains $wolf 'ENT\.LeapIgnoreCliff\s*=\s*true' "Wolf leap should allow close pounces over short gaps instead of treating every support loss as a cliff."
Assert-Contains $wolf 'ENT\.LeapMinDistanceCells\s*=\s*1\.2' "Wolf leap should be allowed from close range when melee is not already in range."
Assert-Contains $wolf 'ENT\.LeapMaxDistanceCells\s*=\s*3\.6' "Wolf leap should stay under roughly 3-4 blocks, not long-range travel."
Assert-Contains $wolf 'ENT\.LeapChance\s*=\s*0\.65' "Wolf leap should use the faster current pounce frequency."
Assert-Contains $wolf 'ENT\.LeapAttemptInterval\s*=\s*0\.3' "Wolf leap should retry eligibility checks more often after the frequency tuning."
Assert-Contains $wolf 'ENT\.LeapCooldownMin\s*=\s*1\.6' "Wolf leap should use the faster current minimum cooldown."
Assert-Contains $wolf 'ENT\.LeapCooldownMax\s*=\s*3\.0' "Wolf leap should use the faster current maximum cooldown."
Assert-Contains $wolf 'ENT\.LeapMaxUpCells\s*=\s*0\.25' "Wolf should not pounce when the target is meaningfully above it."
Assert-Contains $wolf 'ENT\.LeapHorizontalSpeed\s*=\s*300' "Wolf leap should carry farther forward after source-code comparison."
Assert-Contains $wolf 'ENT\.LeapVerticalSpeed\s*=\s*225' "Wolf leap should arc higher after source-code comparison."
Assert-Contains $wolf 'BMB\.Behaviors\.Leap\.Try\(self,\s*self\.TargetEntity\)' "Wolf should try shared leap before falling back to chase."
Assert-Contains $wolf 'self:SetBMBWolfAngry\(IsValid\(self\.TargetEntity\)\)' "Wolf angry skin should stay active for valid combat targets, including leap."
Assert-Contains $behaviors 'BMB\.Behaviors\.Pack\s*=\s*BMB\.Behaviors\.Pack or \{\}' "Wolf Phase 4 should add pack/flank as a shared behavior module."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Pack\.GetMembers\(mob,\s*target\)' "Shared pack should discover same-target pack members."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Pack\.GetFlankDestination\(mob,\s*target\)' "Shared pack should compute a temporary flank destination."
Assert-Contains $behaviors 'FindNearestStandable' "Shared pack flank slots should snap to nearby standable cells instead of raw unsupported offsets."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Pack\.Run\(mob,\s*target\)' "Shared pack should expose a short blocking movement slice."
Assert-Contains $behaviors 'function\s+BMB\.Behaviors\.Pack\.AlertAlliesOnRetaliation\(mob,\s*attacker\)' "Shared pack should expose reusable ally alert on damage retaliation."
Assert-Contains $behaviors 'mob\.PackRetaliationAlertEnabled\s*~=\s*true' "Pack retaliation alert must be explicit opt-in so zombies/skeletons do not group-aggro by default."
Assert-Contains $behaviors 'ally\.PackRetaliationAlertEnabled\s*==\s*true' "Only explicitly opted-in allies should receive pack retaliation alerts."
Assert-Contains $base 'function ENT:MaintainBMBMobSeparation\(\)' "Base mobs should apply a lightweight separation push when BMB mobs overlap."
Assert-Contains $base 'ents\.FindInSphere\(origin,\s*searchRadius\)' "Base mob separation should look for nearby overlapping BMB mobs."
Assert-Contains $base 'MaintainBMBMobSeparation\(\)' "Base Think should run mob separation for every living unheld BMB mob."
Assert-Contains $base 'AlertAlliesOnRetaliation\(self,\s*attacker\)' "Base damage retaliation should be able to alert nearby pack allies."
Assert-Contains $wolf 'ENT\.PackEnabled\s*=\s*true' "Wolf Phase 4 should opt into shared pack/flank behavior."
Assert-Contains $wolf 'ENT\.PackMinMembers\s*=\s*2' "Wolf pack behavior should only engage when another wolf shares the target."
Assert-Contains $wolf 'ENT\.PackFlankRadiusCells\s*=\s*1\.65' "Wolf pack flank radius should stay close enough to re-enter melee/leap quickly."
Assert-Contains $wolf 'ENT\.PackRetaliationAlertEnabled\s*=\s*true' "Wolf pack should alert nearby wolves when one wolf retaliates against a player."
Assert-Contains $wolf 'ENT\.PackRetaliationAlertRadiusCells\s*=\s*8\.0' "Wolf pack retaliation alert should cover a local group without being global."
Assert-Contains $wolf 'BMB\.Behaviors\.Pack\.Run\(self,\s*self\.TargetEntity\)' "Wolf should try pack flank after melee/leap and before normal chase."
Assert-NotContains $wolf 'RangedAttack' "Wolf Phase 4 must not mix in ranged behavior."

Assert-Contains $wolf 'WolfAngrySkinOnChase\s*=\s*true' "Wolf angry state should be an entity-level skin rule for future tame-state rules."
Assert-Contains $wolf 'wolfSkinVariants\s*=\s*\{\s*"woods",\s*"ashen",\s*"black",\s*"chestnut",\s*"rusty",\s*"snowy",\s*"spotted",\s*"striped",\s*"classic"\s*\}' "Wolf skins should use the agreed variant order so skin 0/1 are woods calm/angry."
Assert-Contains $wolf 'CreateConVar\(\s*"bmb_wolf_variant_lock"' "Wolf skin variant should be lockable for testing."
Assert-Contains $wolf 'bmb_wolf_variant_weight_' "Wolf skin spawn weights should be convar-driven."
Assert-Contains $wolf 'self\.variant\s*=\s*variant' "Wolf should store the zero-based variant index on self.variant."
Assert-Contains $wolf 'function ENT:GetBMBWolfDesiredSkin\(\)' "Wolf should derive the actual model skin from variant plus angry state."
Assert-Contains $wolf 'return self:GetBMBWolfSkinVariant\(\) \* 2 \+ angry' "Wolf skin index must be variant*2 + angryBit."
Assert-Contains $wolf 'function ENT:SetBMBWolfAngry\(angry\)' "Wolf angry transitions should update skin through a helper."
Assert-Contains $wolf 'function ENT:ApplyBMBWolfSkinToolSkin\(skin\)' "Skin tool changes should be converted back into wolf variants."
Assert-Contains $wolf 'math\.floor\(skinIndex / 2\)' "Skin tool reverse mapping should use floor(skin/2)."
Assert-Contains $wolf 'function ENT:SetSkin\(skin\)' "Wolf should intercept Lua Skin tool SetSkin calls."
Assert-Contains $wolf 'self:SetBMBWolfSkinVariant\(self:ChooseBMBWolfSkinVariant\(\)\)' "Wolf should choose a random skin variant at spawn."
Assert-Contains $wolf 'BMBWolfAngry' "Wolf should network whether it is currently angry/chasing prey."
Assert-NotContains $wolf 'WolfAngryMaterial|bmb_wolf_angry_texture|MaterialOverride' "Wolf angry visuals must use MDL skin families, not a classic angry material override."

Assert-Contains $behaviors '(?s)if mob\.BMBMoveInterrupt then return false end\s*end\s*if not BMB\.Behaviors\.SeekTarget\.IsValid\(mob,\s*target,\s*mob\.TargetLoseRange or mob\.TargetRange\) then\s*return false\s*end\s*local useClimbPath' "Shared Chase should re-check target validity after direct chase before using target:GetPos()."

Assert-Contains $wolf 'function ENT:CacheBMBWolfBones\(\)' "Wolf should cache MC model bones for visual overlays."
Assert-Contains $wolf '"head",\s*"leg0",\s*"leg1",\s*"leg2",\s*"leg3",\s*"tail"' "Wolf bone cache should cover head, four legs, and tail."
Assert-Contains $wolf 'function ENT:UpdateBMBVisualBones\(\)' "Wolf should update visual bones client-side."
Assert-Contains $wolf 'UpdateBMBLookAtHeadPose\(bones\.head\)' "Wolf should reuse Base LookAt head rendering."
Assert-Contains $wolf 'UpdateBMBLimbSwing\(speed\)' "Wolf should reuse Base continuous limb swing."
Assert-Contains $wolf 'wolfBasePose\s*=\s*\{' "Wolf shipped pose should be code-owned, not dependent on archived client convar defaults."
Assert-Contains $wolf 'upperBody\s*=\s*\{ angle = Angle\(0,\s*0,\s*0\), pos = Vector\(0,\s*0,\s*-10\) \}' "Wolf upperBody base pose should keep the tested -10 z offset even when old convars are reset."
Assert-Contains $wolf 'tail\s*=\s*\{ angle = Angle\(0,\s*0,\s*-45\), pos = Vector\(0,\s*0,\s*0\) \}' "Wolf tail base pose should idle at the tested vanilla-like droop."
Assert-Contains $wolf 'createWolfPoseOffsetConVars\("bmb_wolf_tail"\)' "Wolf tail tuning should use offset convars so saved old defaults cannot erase the base pose."
Assert-Contains $wolf 'tailAngle\.p\s*=\s*tailAngle\.p\s*\+\s*math\.sin\(phase\).*WolfTailSwingXDegrees' "Wolf tail walk/run swing should use rot_x, not the droop rot_z axis."
Assert-Contains $wolf 'WolfTailSwingXDegrees\s*=\s*40' "Wolf tail rot_x should swing naturally between about -40 and 40 while moving."
Assert-Contains $wolf 'createWolfPoseOffsetConVars\("bmb_wolf_body"\)' "Wolf body pose should stay tunable client-side while Phase 0 axes are being verified."
Assert-Contains $wolf 'createWolfPoseOffsetConVars\("bmb_wolf_upper_body"\)' "Wolf upperBody pose should stay tunable client-side while Phase 0 axes are being verified."
Assert-Contains $wolf 'applyWolfPose\(self,\s*bones\.upperBody,\s*"upperBody"\)' "Wolf upperBody base pose should be applied during visual updates."
Assert-Contains $wolf '(?s)resetWolfBones\(self,\s*bones\).*?applyWolfPose\(self,\s*bones\.body,\s*"body"\).*?applyWolfPose\(self,\s*bones\.upperBody,\s*"upperBody"\).*?applyWolfPose\(self,\s*bones\.tail,\s*"tail"\).*?if bones\.root then' "Wolf body/upperBody/tail base pose should also be preserved while dead/tipping."
Assert-Contains $wolf 'leg0.*legSwing' "Wolf should drive one diagonal leg pair."
Assert-Contains $wolf 'leg1.*-legSwing' "Wolf should counter-swing the opposite diagonal leg pair."
Assert-Contains $wolf 'function ENT:MaybePlayStep\(\)' "Wolf should silence Base's placeholder zombie footstep until the wolf sound pass."

Assert-Contains $menu '"bmb_wolf"' "Spawn menu should register BMB Wolf as an NPC."
Assert-Contains $menu 'Name\s*=\s*"BMB Wolf"' "Spawn menu should show the published BMB Wolf name."

Write-Host "Wolf checks passed."
